import { Site } from "./types";

export const initialSites: Site[] = [
  {
    id: "1",
    name: "2TEN Hotel & Convention Centre",
    group: "IND",
    services: ["IPTV", "Casting", "Chromecasts", "HSIA", "WLAN Controller", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.167.143.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.167.143.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.167.143.150/",
    switches: "HP Procurve 1808\nCISCOSW -",
    wlanController: "Ruckus_SZ100-1G",
    wlanControllerUrl: "https://10.167.143.3:8443/wsg/",
    notes: "HOIST VPN/TEC",
    other: "CAST2TV_Fusion"
  },
  {
    id: "2",
    name: "African Sun Bulawayo Zimbabwe",
    group: "African Sun",
    services: ["IPTV", "Casting", "Chromecasts", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.173.172.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.173.172.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.173.172.50/",
    switches: "Brocade ICX 7150",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "N/A",
    other: "CAST2TV_Fusion"
  },
  {
    id: "3",
    name: "African Sun HI Harare Hotel",
    group: "African Sun",
    services: ["IPTV", "Casting", "Chromecasts", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.174.119.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.174.119.1/ods/admin",
    castingUrl: "CLONE USB | http://192.168.100.2/ods/unifiedHTML/",
    headend: "WISI GN50",
    headendUrl: "http://10.174.119.50/",
    switches: "Brocade ICX 7150",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "4",
    name: "Avani - Royal Livingstone",
    group: "MINOR",
    services: ["IPTV", "Casting VIA Heroaps"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "Royal Livingstone http://10.13.3.12:9934/admin/\nAvani http://10.13.3.13:9934/admin/",
    castingUrl: "227.0.0.1:5000\n227.0.1.1:5000",
    headend: "GN40",
    headendUrl: "http://10.13.3.101-107",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: ""
  },
  {
    id: "5",
    name: "Cape Grace",
    group: "?????",
    services: [],
    vpn: "",
    pms: "",
    hsia: "",
    ip: "",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  },
  {
    id: "6",
    name: "Cardoso Hotel Maputo",
    group: "WESTMONT",
    services: ["IPTV", "Casting", "Chromecasts", "HSIA", "WLAN Controller", "APs", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.172.62.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.172.62.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.172.62.50/",
    switches: "Unknown Switch",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "7",
    name: "Century City Hotel Bridgewater & Bridgewater Apartments",
    group: "Century City Hotels",
    services: ["HSIA"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.162.169.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "8",
    name: "Century City Hotel Urban Square",
    group: "Century City Hotels",
    services: ["HSIA"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.135.232.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "9",
    name: "Christel House South Africa, Cape Town School",
    group: "IND",
    services: ["HSIA", "WLAN Controller", "APs", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.162.92.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "Aruba_Instant_AP",
    wlanControllerUrl: "https://tecadmin.sceur.ch/hotspot_landevice_controllerusage.php?LocationCode=AE009241&NASID=AE009241&FormMode=naslookup",
    notes: "",
    other: "n/a"
  },
  {
    id: "10",
    name: "Cresta Grande, Cape Town",
    group: "Cresta",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.172.36.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.172.36.1/ods/admin/",
    castingUrl: "192.168.100.2:80",
    headend: "GN40",
    headendUrl: "http://10.172.36.50-54",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "11",
    name: "Cresta Jwaneng Hotel",
    group: "Cresta",
    services: ["IPTV", "Casting", "Chromecasts", "HSIA", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.174.69.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.174.69.1/ods/admin",
    castingUrl: "192.168.100.2:80",
    headend: "WISI Tangram",
    headendUrl: "http://10.174.69.160/\nhttp://10.174.69.170/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "12",
    name: "Cresta Mahalapye Botswana",
    group: "Cresta",
    services: ["IPTV", "Casting", "Chromecasts", "HSIA", "Switches"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.173.173.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.173.173.1/ods/",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.173.173.160/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "13",
    name: "DeHoek",
    group: "IND",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "http://192.168.2.12:9934/admin",
    castingUrl: "information needed",
    headend: "GN40",
    headendUrl: "http://192.168.2.20-25",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "14",
    name: "Devonvale",
    group: "IND",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "http://192.168.1.97:9934/admin/",
    castingUrl: "GEM | 4900000KHz | 6900 | 256-QAM",
    headend: "GN40",
    headendUrl: "http://192.168.1.241-246",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "15",
    name: "Fancourt Hotel & Golf Estate",
    group: "Fancort Hotels",
    services: ["IPTV", "WLAN Controller", "Switches", "HSIA"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.169.4.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.169.4.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.169.4.240/",
    switches: "n/a",
    wlanController: "Ruckus_SZ100-10G",
    wlanControllerUrl: "https://10.169.4.254:8443/wsg",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "16",
    name: "Four Seasons - The Westcliff",
    group: "Four Seasons",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "http://10.126.148.191:9934/",
    castingUrl: "information needed",
    headend: "WISI GN50",
    headendUrl: "http://10.0.62.220/\nhttp://10.0.62.221/\nhttp://10.0.62.222/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "17",
    name: "Hotel Verde Cape Town Airport",
    group: "Verde",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.167.200.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.167.200.1/ods/admin/",
    castingUrl: "192.168.100.2:80",
    headend: "GN40",
    headendUrl: "http://10.167.200.50-57",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "18",
    name: "Kievits Kroon",
    group: "Kievits",
    services: ["IPTV", "Nodix Casting", "Switches"],
    vpn: "Anydesk\nTeamViewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "",
    castingUrl: "",
    headend: "WISI Tangram",
    headendUrl: "",
    switches: "Aruba Instant On, H3C",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: "Nomadix Casting"
  },
  {
    id: "19",
    name: "Legacy - Bakubung",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach | LG Pro:Centric",
    iptvUrl: "https://localhost/\nhttp://192.168.9.110:9934/admin/",
    castingUrl: "CH87 | 802000 | 6875 | 64QAM\nGEM | 450000KHz | 6900 | 256QAM",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.11/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "20",
    name: "Legacy - Centurion Lake",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach | LG Pro:Centric",
    iptvUrl: "https://localhost/\nhttp://192.168.9.110:9934/admin/",
    castingUrl: "CH87 | 802000 | 6875 | 64QAM\nGEM | 458000KHz | 6900 | 256QAM",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.11/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "21",
    name: "Legacy - Commodore and Portswood",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach",
    iptvUrl: "https://localhost/",
    castingUrl: "\nCH84 | 778000 | 6875 | 64QAM",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.11/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "22",
    name: "Legacy - DaVinci",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach",
    iptvUrl: "https://localhost/",
    castingUrl: "CH87 | 802000 | 6875 | 64QAM",
    headend: "WISI GN50",
    headendUrl: "http://10.0.62.230/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "23",
    name: "Legacy - Kwa-Maritane",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach",
    iptvUrl: "https://localhost/",
    castingUrl: "CH50 | 506000 | 6875 | 64QAM",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.11",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "24",
    name: "Legacy - Windhoek Country Club",
    group: "Legacy",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Samsung Reach | LG Pro:Centric",
    iptvUrl: "https://localhost/\nhttp://192.168.128.102:9934/admin/",
    castingUrl: "CH87 | 802000 | 6875 | 64QAM\nGEM | 402000KHz | 6900 | 256QAM",
    headend: "WISI GN50",
    headendUrl: "http://10.11.111.30/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "25",
    name: "NH - Hotel Sandton",
    group: "NH Hotels",
    services: ["IPTV", "RF", "APs", "Switches"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "GN40",
    headendUrl: "http://10.79.62.81-87",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "26",
    name: "One and Only",
    group: "Kerzner International",
    services: ["IPTV"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "Acentic",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "WISI GN50",
    headendUrl: "http://192.168.1.30",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "27",
    name: "Queen Victoria Hotel V & A Waterfront",
    group: "",
    services: ["????"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.173.204.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.173.204.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.173.23.50/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "28",
    name: "Qwabi - Babohi",
    group: "Newmark",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.50/\nhttp://192.168.0.70/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "29",
    name: "Qwabi - Letamo",
    group: "Newmark",
    services: ["IPTV", "RF"],
    vpn: "Team Viewer",
    pms: "n/a",
    hsia: "n/a",
    ip: "-",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "WISI GN50",
    headendUrl: "http://192.168.0.50/\nhttp://192.168.0.70/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "30",
    name: "Southern Sun - 54 on Bath",
    group: "SouthernSun – Deluxe",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.194.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "31",
    name: "Southern Sun - Arabella Hotel Golf & Spa",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.169.133.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "32",
    name: "Southern Sun - Beacon Island Resort",
    group: "Southern Sun - Resort",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.168.29.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "33",
    name: "Southern Sun - Beverly Hills Hotel",
    group: "SouthernSun – Deluxe",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.189.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "34",
    name: "Southern Sun - Bloemfontein",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.146.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "35",
    name: "Southern Sun - Cabana Beach Resort",
    group: "Southern Sun - Resort",
    services: ["IPTV", "PCA"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.165.67.1",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "a",
    castingUrl: "GEM | 227.1.1.1:5000\nGEM | 458000KHz | 6900 | 256QAM",
    headend: "WISI GN50",
    headendUrl: "http://10.165.67.10/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "36",
    name: "Southern Sun - Cape Town",
    group: "SouthernSun – Southern Sun",
    services: ["???"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.147.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "37",
    name: "Southern Sun - Drakensberg Sun Resort",
    group: "Southern Sun - Resort",
    services: ["???"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.164.160.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "38",
    name: "Southern Sun - Elangeni & Maharani",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.218.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "39",
    name: "Southern Sun - Emnotweni",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.149.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "40",
    name: "Southern Sun - Garden Court East London",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.164.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "41",
    name: "Southern Sun - Garden Court Eastgate",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.81.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "42",
    name: "Southern Sun - Garden Court Hatfield",
    group: "SouthernSun – Garden Court",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.165.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "43",
    name: "Southern Sun - Garden Court Kimberley",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.166.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "44",
    name: "Southern Sun - Garden Court Kings Beach",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.167.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "45",
    name: "Southern Sun - Garden Court Marine Parade",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.168.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "46",
    name: "Southern Sun - Garden Court Milpark",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.169.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "47",
    name: "Southern Sun - Garden Court Morningside Sandton",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.170.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "48",
    name: "Southern Sun - Garden Court Mthatha",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.177.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "49",
    name: "Southern Sun - Garden Court Nelson Mandela Boulevard",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.171.186.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "50",
    name: "Southern Sun - Garden Court O.R Tambo International Airport",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.171.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "51",
    name: "Southern Sun - Garden Court Polokwane",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.172.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "52",
    name: "Southern Sun - Garden Court Sandton City",
    group: "SouthernSun – Garden Court",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.173.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "53",
    name: "Southern Sun - Garden Court South Beach",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.174.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "54",
    name: "Southern Sun - Garden Court Ulundi",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.175.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "55",
    name: "Southern Sun - Garden Court Umhlanga",
    group: "SouthernSun – Garden Court",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.176.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "56",
    name: "Southern Sun - Garden Court Victoria Junction",
    group: "SouthernSun – Garden Court",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.163.128.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "57",
    name: "Southern Sun - Hazyview Sun",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.169.132.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "58",
    name: "Southern Sun - Hyde Park Sandton",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.150.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.164.150.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI Tangram",
    headendUrl: "http://10.164.150.160",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "59",
    name: "Southern Sun - IC Airport OR Tambo",
    group: "SouthernSun – Deluxe",
    services: ["MCOMMS", "Headend", "???"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.190.1",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  },
  {
    id: "60",
    name: "Southern Sun - Katherine Street Sandton",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.151.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "61",
    name: "Southern Sun - Maputo",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.159.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "62",
    name: "Southern Sun - Mount Grace Hotel & Spa",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV", "WLAN Controller", "Switches", "HSIA", "Aps"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.169.134.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "WISI GN50",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "Ruckus_ZD3050",
    wlanControllerUrl: "https://10.169.134.13/admin10/login.jsp",
    notes: "HOIST VPN/TEC",
    other: "n/a"
  },
  {
    id: "63",
    name: "Southern Sun - Newlands",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV", "WLAN Controller", "Switches", "HSIA", "Aps", "One80"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.153.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "64",
    name: "Southern Sun - O.R. Tambo International Airport",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.154.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "65",
    name: "Southern Sun - Pretoria",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.155.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "66",
    name: "Southern Sun - Riverside Sun",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.161.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "67",
    name: "Southern Sun - Rosebank",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.167.230.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "http://10.167.230.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI Tangram",
    headendUrl: "http://10.167.230.50/\nhttp://10.167.230.60/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "68",
    name: "Southern Sun - Sabi River Sun Resort",
    group: "Southern Sun - Resort",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.164.162.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "69",
    name: "Southern Sun - Sandton",
    group: "Southern Sun - Resort",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.167.231.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.167.231.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.167.231.85/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "70",
    name: "Southern Sun - Sandton Convention Centre",
    group: "SouthernSun – Southern Sun",
    services: ["Signage CMS LG"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.164.188.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "71",
    name: "Southern Sun - Sandton Sun",
    group: "SouthernSun – Deluxe",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.193.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "72",
    name: "Southern Sun - Sandton Towers",
    group: "SouthernSun – Deluxe",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.191.1",
    iptvSystem: "LG Pro:Centric",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "73",
    name: "Southern Sun - Stay Easy Emnotweni - Nelspruit",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.180.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "74",
    name: "Southern Sun - StayEasy Cape Town, City Bowl",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.184.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "75",
    name: "Southern Sun - StayEasy Century City",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.178.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "76",
    name: "Southern Sun - StayEasy Eastgate",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.179.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "77",
    name: "Southern Sun - StayEasy Pietermaritzburg",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.182.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "78",
    name: "Southern Sun - StayEasy Pretoria",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.183.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "79",
    name: "Southern Sun - StayEasy Rustenburg",
    group: "SouthernSun – Stay Easy",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.185.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "80",
    name: "Southern Sun - Sun Square - Cape Town City Bowl",
    group: "SouthernSun – Sun Square",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.187.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "81",
    name: "Southern Sun - Sun Square Cape Town Gardens",
    group: "SouthernSun – Sun Square",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.163.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "82",
    name: "Southern Sun - The Cullinan",
    group: "SouthernSun – Southern Sun",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.157.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.164.157.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI Tangram",
    headendUrl: "http://10.164.157.50/\nhttp://10.164.157.60/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "83",
    name: "Southern Sun - The Edward Hotel, Durban",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.169.113.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "84",
    name: "Southern Sun - The Marine, Port Elizabeth",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.170.122.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "85",
    name: "Southern Sun - uMhlanga Sands Resort",
    group: "Southern Sun - Resort",
    services: ["Headend", "IPTV (Reach)"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.165.67.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "86",
    name: "Southern Sun - Waterfront Cape Town",
    group: "SouthernSun – Southern Sun",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.158.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "87",
    name: "The Oyster Box Hotel",
    group: "",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.172.244.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.172.244.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.172.244.50/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "88",
    name: "The Victoria Falls Hotel",
    group: "African Sun",
    services: ["IPTV", "IPTV (RF)"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.171.44.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.171.46.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.171.46.30/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "89",
    name: "Tsogo Sun - Hemingways Hotel",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.145.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "90",
    name: "Tsogo Sun - Hotel Perte",
    group: "Tsogo Sun - Gaming",
    services: ["IPTV"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.168.90.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.168.90.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.168.90.50/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "91",
    name: "Tsogo Sun - Palazzo Montecasino",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.192.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "92",
    name: "Tsogo Sun - Piazza Montecasino",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.186.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "93",
    name: "Tsogo Sun - Pivot Montecasino",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.152.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "94",
    name: "Tsogo Sun - Suncoast Hotel & Towers",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.156.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "95",
    name: "Tsogo Sun - The Ridge Hotel",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.167.232.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "96",
    name: "Tsogo Sun - The Ridge Point Hotel",
    group: "Tsogo Sun - Gaming",
    services: ["WLAN Controller", "Switches", "AP's"],
    vpn: "Hoist/Planet -VPN",
    pms: "Fidelio Opera PMS",
    hsia: "Fusion Hummingbird",
    ip: "10.164.181.1",
    iptvSystem: "n/a",
    iptvUrl: "-",
    castingUrl: "-",
    headend: "n/a",
    headendUrl: "-",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "n/a"
  },
  {
    id: "97",
    name: "Victoria & Alfred Hotel Cape Town",
    group: "",
    services: ["???"],
    vpn: "Hoist/Planet -VPN",
    pms: "n/a",
    hsia: "Fusion Hummingbird",
    ip: "10.173.23.1",
    iptvSystem: "Fusion IPTV",
    iptvUrl: "https://10.173.23.1/ods",
    castingUrl: "192.168.100.2:80",
    headend: "WISI GN50",
    headendUrl: "http://10.173.23.50/",
    switches: "n/a",
    wlanController: "n/a",
    wlanControllerUrl: "-",
    notes: "",
    other: "CAST2TV_Fusion"
  },
  {
    id: "98",
    name: "Golden valley",
    group: "Sun International",
    services: ["Headend"],
    vpn: "Team Viewer",
    pms: "",
    hsia: "",
    ip: "",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  },
  {
    id: "99",
    name: "IC Tablebay",
    group: "Inter Continental",
    services: ["IPTV", "Headend", "Signage"],
    vpn: "Team Viewer",
    pms: "",
    hsia: "",
    ip: "",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  },
  {
    id: "100",
    name: "IHG Dar es Salaam Crown Plaza",
    group: "IHG",
    services: ["Heroapps (IPTV)", "Headend (NUC)"],
    vpn: "Team Viewer",
    pms: "",
    hsia: "",
    ip: "",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  },
  {
    id: "101",
    name: "VOD Media LAB (Blaauwklippen)",
    group: "Newmark",
    services: ["IPTV", "HSIA"],
    vpn: "Hoist/Planet -VPN",
    pms: "",
    hsia: "Fusion Hummingbird",
    ip: "10.164.104.1",
    iptvSystem: "",
    iptvUrl: "",
    castingUrl: "",
    headend: "",
    headendUrl: "",
    switches: "",
    wlanController: "",
    wlanControllerUrl: "",
    notes: "",
    other: ""
  }
];
